---
  - name: get dev tools
    hosts: hosts
    become: yes

    tasks:

        # NodeJS related tasks
        - name: add apt key for node
          apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key

        - name: add repo for node
          apt_repository: repo: 'deb https://deb.nodesource.com/node_0.10 {{ ansible_distribution_release }} main'
          update_cache: yes

        - name: install node package
          apt: name=nodejs

        # Install VIM text editor
        - name: install vim
          apt: name=vim state=present
